name: Test actions

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set RELEASE_VERSION
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Build the Docker image version ${{ env.RELEASE_VERSION }}
      run: docker build .  --tag krokas/test-image:latest
  push:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Push image version ${{ env.RELEASE_VERSION }} to docker hub
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: krokas/test-image
        tags: krokas/test-image:latest
