name: Test actions

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: getlatesttag
      uses: "WyriHaximus/github-action-get-previous-tag@v1"
      id: previoustag
    - name: Set RELEASE_VERSION
      run: echo "RELEASE_VERSION=${{ steps.previoustag.outputs.tag }}" >> $GITHUB_ENV
    - name: Build the Docker image version ${{ env.RELEASE_VERSION }}
      run: docker build .  --tag krokas/test-image:${{ env.RELEASE_VERSION }}
  push:
    runs-on: ubuntu-latest
    steps:
    - name: Push image version ${{ env.RELEASE_VERSION }} to docker hub
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: krokas/test-image
        tags: krokas/test-image:${{ env.RELEASE_VERSION }}
