name: Test actions

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build-image:
    runs-on: ubuntu-latest
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - uses: actions/checkout@v2
    - name: Set RELEASE_VERSION
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Build and push image version ${{ env.RELEASE_VERSION }}
      uses: docker/build-push-action@v2
      with:
        tags: krokas/test-image:latest
        push: true
